/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hamgod
 */
public class MagicalMathMethods extends javax.swing.JFrame {

    /**
     * Creates new form MagicalMathMethods
     */
    public MagicalMathMethods() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelDescription1 = new javax.swing.JLabel();
        LabelTitle = new javax.swing.JLabel();
        BoxNum1_1 = new javax.swing.JTextField();
        BoxNum2_1 = new javax.swing.JTextField();
        ButtonCalc1_1 = new javax.swing.JToggleButton();
        LabelResult1_1 = new javax.swing.JLabel();
        LabelResult1_2 = new javax.swing.JLabel();
        LabelDescription2 = new javax.swing.JLabel();
        ButtonCalc1_2 = new javax.swing.JToggleButton();
        BoxNum2_2 = new javax.swing.JTextField();
        BoxNum1_2 = new javax.swing.JTextField();
        LabelDescription3 = new javax.swing.JLabel();
        BoxNum1_3 = new javax.swing.JTextField();
        BoxNum2_3 = new javax.swing.JTextField();
        ButtonCalc1_3 = new javax.swing.JToggleButton();
        LabelResult1_3 = new javax.swing.JLabel();
        LabelDescription4 = new javax.swing.JLabel();
        BoxNum1_4 = new javax.swing.JTextField();
        BoxNum2_4 = new javax.swing.JTextField();
        ButtonCalc1_4 = new javax.swing.JToggleButton();
        LabelResult1_4 = new javax.swing.JLabel();
        LabelDescription5 = new javax.swing.JLabel();
        BoxNum1_5 = new javax.swing.JTextField();
        ButtonCalc1_5 = new javax.swing.JToggleButton();
        LabelResult1_5 = new javax.swing.JLabel();
        LabelDescription6 = new javax.swing.JLabel();
        BoxNum1_6 = new javax.swing.JTextField();
        ButtonCalc1_6 = new javax.swing.JToggleButton();
        LabelResult1_6 = new javax.swing.JLabel();
        LabelDescription7 = new javax.swing.JLabel();
        BoxNum1_7 = new javax.swing.JTextField();
        ButtonCalc1_7 = new javax.swing.JToggleButton();
        LabelResult1_7 = new javax.swing.JLabel();
        LabelDescription8 = new javax.swing.JLabel();
        BoxNum1_8 = new javax.swing.JTextField();
        ButtonCalc1_8 = new javax.swing.JToggleButton();
        LabelResult1_8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelDescription1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelDescription1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelDescription1.setText("Enter two numbers and the program will show the largerst number of the two");

        LabelTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        LabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTitle.setText("MAGICAL MATH METHODS");

        ButtonCalc1_1.setText("Largest");
        ButtonCalc1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCalc1_1ActionPerformed(evt);
            }
        });

        LabelResult1_1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelResult1_1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelResult1_1.setText("-/-");

        LabelResult1_2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelResult1_2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelResult1_2.setText("-/-");

        LabelDescription2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelDescription2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelDescription2.setText("Enter two numbers and the program will show the smallest number of the two");

        ButtonCalc1_2.setText("Smallest");
        ButtonCalc1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCalc1_2ActionPerformed(evt);
            }
        });

        LabelDescription3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelDescription3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelDescription3.setText("Enter two numbers and the program will show the number to the power of the other");

        ButtonCalc1_3.setText("Power of");
        ButtonCalc1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCalc1_3ActionPerformed(evt);
            }
        });

        LabelResult1_3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelResult1_3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelResult1_3.setText("-/-");

        LabelDescription4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelDescription4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelDescription4.setText("Enter two lengths of a triangle and the program will show the hypotenuse of the triangle");

        ButtonCalc1_4.setText("Hypotenuse");
        ButtonCalc1_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCalc1_4ActionPerformed(evt);
            }
        });

        LabelResult1_4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelResult1_4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelResult1_4.setText("-/-");

        LabelDescription5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelDescription5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelDescription5.setText("Enter a decimal value and the program will round down to the nearest integer");

        ButtonCalc1_5.setText("Round down");
        ButtonCalc1_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCalc1_5ActionPerformed(evt);
            }
        });

        LabelResult1_5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelResult1_5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelResult1_5.setText("-/-");

        LabelDescription6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelDescription6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelDescription6.setText("Enter a decimal value and the program will round up to the nearest integer");

        BoxNum1_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxNum1_6ActionPerformed(evt);
            }
        });

        ButtonCalc1_6.setText("Round up");
        ButtonCalc1_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCalc1_6ActionPerformed(evt);
            }
        });

        LabelResult1_6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelResult1_6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelResult1_6.setText("-/-");

        LabelDescription7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelDescription7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelDescription7.setText("Enter an integer and the program will show the square root of that integer");

        ButtonCalc1_7.setText("Square root");
        ButtonCalc1_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCalc1_7ActionPerformed(evt);
            }
        });

        LabelResult1_7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelResult1_7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelResult1_7.setText("-/-");

        LabelDescription8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelDescription8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelDescription8.setText("Enter an angle in degrees and the program will show the angle in radians");

        ButtonCalc1_8.setText("Radians");
        ButtonCalc1_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCalc1_8ActionPerformed(evt);
            }
        });

        LabelResult1_8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelResult1_8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelResult1_8.setText("-/-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(BoxNum1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(BoxNum2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(ButtonCalc1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelResult1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BoxNum1_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(215, 215, 215)
                                .addComponent(ButtonCalc1_8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelResult1_8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelDescription2)
                                    .addComponent(LabelDescription3, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelDescription5)
                                    .addComponent(LabelDescription6)
                                    .addComponent(LabelDescription7)
                                    .addComponent(LabelDescription8)
                                    .addComponent(LabelDescription4))
                                .addGap(0, 5, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BoxNum1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(215, 215, 215)
                                .addComponent(ButtonCalc1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelResult1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BoxNum1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(215, 215, 215)
                                .addComponent(ButtonCalc1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelResult1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BoxNum1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(215, 215, 215)
                                .addComponent(ButtonCalc1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelResult1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BoxNum1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(BoxNum2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120)
                                .addComponent(ButtonCalc1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelResult1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BoxNum1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(BoxNum2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120)
                                .addComponent(ButtonCalc1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelResult1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BoxNum1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(BoxNum2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120)
                                .addComponent(ButtonCalc1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelResult1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelDescription1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(LabelDescription1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoxNum1_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxNum2_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelResult1_1)
                    .addComponent(ButtonCalc1_1))
                .addGap(18, 18, 18)
                .addComponent(LabelDescription2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoxNum1_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxNum2_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelResult1_2)
                    .addComponent(ButtonCalc1_2))
                .addGap(18, 18, 18)
                .addComponent(LabelDescription3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoxNum1_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxNum2_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelResult1_3)
                    .addComponent(ButtonCalc1_3))
                .addGap(18, 18, 18)
                .addComponent(LabelDescription4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoxNum1_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxNum2_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelResult1_4)
                    .addComponent(ButtonCalc1_4))
                .addGap(18, 18, 18)
                .addComponent(LabelDescription5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoxNum1_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelResult1_5)
                    .addComponent(ButtonCalc1_5))
                .addGap(18, 18, 18)
                .addComponent(LabelDescription6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoxNum1_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelResult1_6)
                    .addComponent(ButtonCalc1_6))
                .addGap(18, 18, 18)
                .addComponent(LabelDescription7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoxNum1_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelResult1_7)
                    .addComponent(ButtonCalc1_7))
                .addGap(18, 18, 18)
                .addComponent(LabelDescription8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoxNum1_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelResult1_8)
                    .addComponent(ButtonCalc1_8))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCalc1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCalc1_1ActionPerformed
        // TODO add your handling code here:
        int iNum1 = Integer.parseInt(BoxNum1_1.getText());
        int iNum2 = Integer.parseInt(BoxNum2_1.getText());
        
        int iLarger = Math.max(iNum1,iNum2);
        
        LabelResult1_1.setText(String.valueOf(iLarger));
    }//GEN-LAST:event_ButtonCalc1_1ActionPerformed

    private void ButtonCalc1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCalc1_2ActionPerformed
        // TODO add your handling code here:
        int iNum1 = Integer.parseInt(BoxNum1_2.getText());
        int iNum2 = Integer.parseInt(BoxNum2_2.getText());
        
        int iSmaller = Math.min(iNum1,iNum2);
        
        LabelResult1_2.setText(String.valueOf(iSmaller));
    }//GEN-LAST:event_ButtonCalc1_2ActionPerformed

    private void ButtonCalc1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCalc1_3ActionPerformed
        // TODO add your handling code here:
        int iNum1 = Integer.parseInt(BoxNum1_3.getText());
        int iNum2 = Integer.parseInt(BoxNum2_3.getText());
        
        int iPow = (int) Math.pow(iNum1,iNum2);
        
        LabelResult1_3.setText(String.valueOf(iPow));
    }//GEN-LAST:event_ButtonCalc1_3ActionPerformed

    private void ButtonCalc1_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCalc1_4ActionPerformed
        // TODO add your handling code here:
        int iNum1 = Integer.parseInt(BoxNum1_4.getText());
        int iNum2 = Integer.parseInt(BoxNum2_4.getText());
        
        double iPow1 = (int) Math.pow(iNum1,2);
        double iPow2 = (int) Math.pow(iNum2,2);
        
        double dHyp = Math.sqrt(iPow1+iPow2);
        String sHyp = String.format("%.2f",dHyp);
        
        LabelResult1_4.setText(sHyp);
    }//GEN-LAST:event_ButtonCalc1_4ActionPerformed

    private void ButtonCalc1_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCalc1_5ActionPerformed
        // TODO add your handling code here:
        double iNum = Double.parseDouble(BoxNum1_5.getText());
        
        int iRound = (int) Math.floor(iNum);
        
        LabelResult1_5.setText(String.valueOf(iRound));
    }//GEN-LAST:event_ButtonCalc1_5ActionPerformed

    private void ButtonCalc1_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCalc1_6ActionPerformed
        // TODO add your handling code here:
        double iNum = Double.parseDouble(BoxNum1_6.getText());
        
        int iRound = (int)Math.ceil(iNum);
        
        LabelResult1_6.setText(String.valueOf(iRound));
    }//GEN-LAST:event_ButtonCalc1_6ActionPerformed

    private void ButtonCalc1_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCalc1_7ActionPerformed
        // TODO add your handling code here:
        int iNum = Integer.parseInt(BoxNum1_7.getText());
        
        double dRoot = Math.sqrt(iNum);
        String sRoot = String.format("%.2f",dRoot);
        
        LabelResult1_7.setText(sRoot);
    }//GEN-LAST:event_ButtonCalc1_7ActionPerformed

    private void ButtonCalc1_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCalc1_8ActionPerformed
        // TODO add your handling code here:
        double iNum = Double.parseDouble(BoxNum1_8.getText());
        
        double dRad = Math.toRadians(iNum);
        String sRad = String.format("%.2f",dRad);
        
        LabelResult1_8.setText(sRad);
    }//GEN-LAST:event_ButtonCalc1_8ActionPerformed

    private void BoxNum1_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxNum1_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxNum1_6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MagicalMathMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MagicalMathMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MagicalMathMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MagicalMathMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MagicalMathMethods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BoxNum1_1;
    private javax.swing.JTextField BoxNum1_2;
    private javax.swing.JTextField BoxNum1_3;
    private javax.swing.JTextField BoxNum1_4;
    private javax.swing.JTextField BoxNum1_5;
    private javax.swing.JTextField BoxNum1_6;
    private javax.swing.JTextField BoxNum1_7;
    private javax.swing.JTextField BoxNum1_8;
    private javax.swing.JTextField BoxNum2_1;
    private javax.swing.JTextField BoxNum2_2;
    private javax.swing.JTextField BoxNum2_3;
    private javax.swing.JTextField BoxNum2_4;
    private javax.swing.JToggleButton ButtonCalc1_1;
    private javax.swing.JToggleButton ButtonCalc1_2;
    private javax.swing.JToggleButton ButtonCalc1_3;
    private javax.swing.JToggleButton ButtonCalc1_4;
    private javax.swing.JToggleButton ButtonCalc1_5;
    private javax.swing.JToggleButton ButtonCalc1_6;
    private javax.swing.JToggleButton ButtonCalc1_7;
    private javax.swing.JToggleButton ButtonCalc1_8;
    private javax.swing.JLabel LabelDescription1;
    private javax.swing.JLabel LabelDescription2;
    private javax.swing.JLabel LabelDescription3;
    private javax.swing.JLabel LabelDescription4;
    private javax.swing.JLabel LabelDescription5;
    private javax.swing.JLabel LabelDescription6;
    private javax.swing.JLabel LabelDescription7;
    private javax.swing.JLabel LabelDescription8;
    private javax.swing.JLabel LabelResult1_1;
    private javax.swing.JLabel LabelResult1_2;
    private javax.swing.JLabel LabelResult1_3;
    private javax.swing.JLabel LabelResult1_4;
    private javax.swing.JLabel LabelResult1_5;
    private javax.swing.JLabel LabelResult1_6;
    private javax.swing.JLabel LabelResult1_7;
    private javax.swing.JLabel LabelResult1_8;
    private javax.swing.JLabel LabelTitle;
    // End of variables declaration//GEN-END:variables
}
