/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hamgod
 */
public class SuperString extends javax.swing.JFrame {

    /**
     * Creates new form SuperString
     */
    public SuperString() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelDescription1 = new javax.swing.JLabel();
        LabelTitle = new javax.swing.JLabel();
        BoxString1 = new javax.swing.JTextField();
        ButtonCalc1_1 = new javax.swing.JToggleButton();
        LabelResult1_1 = new javax.swing.JLabel();
        LabelResult1_2 = new javax.swing.JLabel();
        LabelDescription2 = new javax.swing.JLabel();
        ButtonCalc1_2 = new javax.swing.JToggleButton();
        BoxString2 = new javax.swing.JTextField();
        LabelDescription3 = new javax.swing.JLabel();
        BoxString3 = new javax.swing.JTextField();
        ButtonCalc1_3 = new javax.swing.JToggleButton();
        LabelResult1_3 = new javax.swing.JLabel();
        LabelDescription4 = new javax.swing.JLabel();
        BoxString4_1 = new javax.swing.JTextField();
        BoxString4_2 = new javax.swing.JTextField();
        ButtonCalc1_4 = new javax.swing.JToggleButton();
        LabelResult1_4 = new javax.swing.JLabel();
        LabelDescription5 = new javax.swing.JLabel();
        BoxString5_1 = new javax.swing.JTextField();
        ButtonCalc1_5 = new javax.swing.JToggleButton();
        LabelResult1_5 = new javax.swing.JLabel();
        LabelDescription6 = new javax.swing.JLabel();
        BoxString6 = new javax.swing.JTextField();
        ButtonCalc1_6 = new javax.swing.JToggleButton();
        LabelResult1_6 = new javax.swing.JLabel();
        LabelDescription7 = new javax.swing.JLabel();
        BoxString7 = new javax.swing.JTextField();
        ButtonCalc1_7 = new javax.swing.JToggleButton();
        LabelResult1_7 = new javax.swing.JLabel();
        BoxString5_2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelDescription1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelDescription1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelDescription1.setText("Enter a string and the program will output its length");

        LabelTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        LabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTitle.setText("SUPER STRING SOFTWARE");

        ButtonCalc1_1.setText("Length");
        ButtonCalc1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCalc1_1ActionPerformed(evt);
            }
        });

        LabelResult1_1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelResult1_1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelResult1_1.setText("-/-");

        LabelResult1_2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelResult1_2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelResult1_2.setText("-/-");

        LabelDescription2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelDescription2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelDescription2.setText("Enter a string in all lowercase and the program will output it in all uppercase");

        ButtonCalc1_2.setText("All Caps");
        ButtonCalc1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCalc1_2ActionPerformed(evt);
            }
        });

        LabelDescription3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelDescription3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelDescription3.setText("Enter a string and the program will enter its 4th character");

        ButtonCalc1_3.setText("4th Letter");
        ButtonCalc1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCalc1_3ActionPerformed(evt);
            }
        });

        LabelResult1_3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelResult1_3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelResult1_3.setText("-/-");

        LabelDescription4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelDescription4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelDescription4.setText("Enter two strings and the program will determine if they are identical");

        ButtonCalc1_4.setText("Identical?");
        ButtonCalc1_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCalc1_4ActionPerformed(evt);
            }
        });

        LabelResult1_4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelResult1_4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelResult1_4.setText("-/-");

        LabelDescription5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelDescription5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelDescription5.setText("Enter a string and a character and the program will output if the string contains it");

        ButtonCalc1_5.setText("Letter Found?");
        ButtonCalc1_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCalc1_5ActionPerformed(evt);
            }
        });

        LabelResult1_5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelResult1_5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelResult1_5.setText("-/-");

        LabelDescription6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelDescription6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelDescription6.setText("Enter a string that is 8 letters long and the program will output its characters from 4 to 6");

        BoxString6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxString6ActionPerformed(evt);
            }
        });

        ButtonCalc1_6.setText("Chars 4 to 6");
        ButtonCalc1_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCalc1_6ActionPerformed(evt);
            }
        });

        LabelResult1_6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelResult1_6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelResult1_6.setText("-/-");

        LabelDescription7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelDescription7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelDescription7.setText("Enter a string that contains at least one \"a\" and the program will replace all \"a\"s with x");

        ButtonCalc1_7.setText("Replace a");
        ButtonCalc1_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCalc1_7ActionPerformed(evt);
            }
        });

        LabelResult1_7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelResult1_7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelResult1_7.setText("-/-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BoxString7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(279, 279, 279)
                            .addComponent(ButtonCalc1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BoxString3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(279, 279, 279)
                            .addComponent(ButtonCalc1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BoxString4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(BoxString4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(111, 111, 111)
                            .addComponent(ButtonCalc1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BoxString5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(BoxString5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(231, 231, 231)
                            .addComponent(ButtonCalc1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelDescription2)
                            .addComponent(LabelDescription5)
                            .addComponent(LabelDescription6)
                            .addComponent(LabelDescription7)
                            .addComponent(LabelDescription4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ButtonCalc1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LabelDescription3, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ButtonCalc1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(ButtonCalc1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelDescription1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BoxString1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(BoxString2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxString6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelResult1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelResult1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelResult1_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelResult1_3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelResult1_4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelResult1_5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelResult1_7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(LabelDescription1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelResult1_1)
                        .addComponent(ButtonCalc1_1))
                    .addComponent(BoxString1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LabelDescription2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelResult1_2)
                        .addComponent(ButtonCalc1_2))
                    .addComponent(BoxString2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LabelDescription3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelResult1_3)
                        .addComponent(ButtonCalc1_3))
                    .addComponent(BoxString3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LabelDescription4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelResult1_4)
                        .addComponent(ButtonCalc1_4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BoxString4_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BoxString4_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(LabelDescription5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelResult1_5)
                        .addComponent(ButtonCalc1_5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BoxString5_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BoxString5_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(LabelDescription6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelResult1_6)
                        .addComponent(ButtonCalc1_6))
                    .addComponent(BoxString6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LabelDescription7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelResult1_7)
                        .addComponent(ButtonCalc1_7))
                    .addComponent(BoxString7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCalc1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCalc1_1ActionPerformed
        // TODO add your handling code here:
        String sInput = BoxString1.getText();
        
        LabelResult1_1.setText(String.valueOf(sInput.length()));
    }//GEN-LAST:event_ButtonCalc1_1ActionPerformed

    private void ButtonCalc1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCalc1_2ActionPerformed
        // TODO add your handling code here:
        String sInput = BoxString2.getText();
        
        LabelResult1_2.setText(sInput.toUpperCase());
    }//GEN-LAST:event_ButtonCalc1_2ActionPerformed

    private void ButtonCalc1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCalc1_3ActionPerformed
        // TODO add your handling code here:
        String sInput = BoxString3.getText();
        
        LabelResult1_3.setText(String.valueOf(sInput.charAt(3)));
    }//GEN-LAST:event_ButtonCalc1_3ActionPerformed

    private void ButtonCalc1_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCalc1_4ActionPerformed
        // TODO add your handling code here:
        String sInput1 = BoxString4_1.getText();
        String sInput2 = BoxString4_2.getText();
        
        if(sInput1.equals(sInput2)){
            LabelResult1_4.setText("Yes");
        }else{
            LabelResult1_4.setText("No");
        }
    }//GEN-LAST:event_ButtonCalc1_4ActionPerformed

    private void ButtonCalc1_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCalc1_5ActionPerformed
        // TODO add your handling code here:
        String sInput = BoxString5_1.getText();
        String sChar = BoxString5_2.getText();
        
        if(sInput.contains(sChar)){
            LabelResult1_5.setText("Yes");
        }else{
            LabelResult1_5.setText("No");
        }
    }//GEN-LAST:event_ButtonCalc1_5ActionPerformed

    private void ButtonCalc1_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCalc1_6ActionPerformed
        // TODO add your handling code here:
        String sInput = BoxString6.getText();
        String sSub = sInput.substring(3,5);
        
        LabelResult1_6.setText(sSub);
    }//GEN-LAST:event_ButtonCalc1_6ActionPerformed

    private void ButtonCalc1_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCalc1_7ActionPerformed
        // TODO add your handling code here:
        String sInput = BoxString7.getText();
        
        LabelResult1_7.setText(sInput.replace("a", "x"));
    }//GEN-LAST:event_ButtonCalc1_7ActionPerformed

    private void BoxString6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxString6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxString6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuperString.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuperString.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuperString.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuperString.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuperString().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BoxString1;
    private javax.swing.JTextField BoxString2;
    private javax.swing.JTextField BoxString3;
    private javax.swing.JTextField BoxString4_1;
    private javax.swing.JTextField BoxString4_2;
    private javax.swing.JTextField BoxString5_1;
    private javax.swing.JTextField BoxString5_2;
    private javax.swing.JTextField BoxString6;
    private javax.swing.JTextField BoxString7;
    private javax.swing.JToggleButton ButtonCalc1_1;
    private javax.swing.JToggleButton ButtonCalc1_2;
    private javax.swing.JToggleButton ButtonCalc1_3;
    private javax.swing.JToggleButton ButtonCalc1_4;
    private javax.swing.JToggleButton ButtonCalc1_5;
    private javax.swing.JToggleButton ButtonCalc1_6;
    private javax.swing.JToggleButton ButtonCalc1_7;
    private javax.swing.JLabel LabelDescription1;
    private javax.swing.JLabel LabelDescription2;
    private javax.swing.JLabel LabelDescription3;
    private javax.swing.JLabel LabelDescription4;
    private javax.swing.JLabel LabelDescription5;
    private javax.swing.JLabel LabelDescription6;
    private javax.swing.JLabel LabelDescription7;
    private javax.swing.JLabel LabelResult1_1;
    private javax.swing.JLabel LabelResult1_2;
    private javax.swing.JLabel LabelResult1_3;
    private javax.swing.JLabel LabelResult1_4;
    private javax.swing.JLabel LabelResult1_5;
    private javax.swing.JLabel LabelResult1_6;
    private javax.swing.JLabel LabelResult1_7;
    private javax.swing.JLabel LabelTitle;
    // End of variables declaration//GEN-END:variables
}
