/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hamgod
 */
public class PositivePractice extends javax.swing.JFrame {

    /**
     * Creates new form PositivePractice
     */
    public PositivePractice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelTitle = new javax.swing.JLabel();
        LabelDescription1 = new javax.swing.JLabel();
        ButtonGenerateQuote = new javax.swing.JToggleButton();
        LabelQuote = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelTitle.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        LabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTitle.setText("Positive Practice!");

        LabelDescription1.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        LabelDescription1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDescription1.setText("Click the Generate Quote button for a positive quote!");

        ButtonGenerateQuote.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        ButtonGenerateQuote.setText("Generate Quote");
        ButtonGenerateQuote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGenerateQuoteActionPerformed(evt);
            }
        });

        LabelQuote.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        LabelQuote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelQuote.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelQuote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(ButtonGenerateQuote, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelDescription1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(LabelTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTitle)
                .addGap(18, 18, 18)
                .addComponent(LabelDescription1)
                .addGap(18, 18, 18)
                .addComponent(ButtonGenerateQuote, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelQuote)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonGenerateQuoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGenerateQuoteActionPerformed
        // TODO add your handling code here:
        int iRandom = (int)(Math.random()*8+1);//Random integer 1-8
        
        switch(iRandom){//8 cases
            case 1:
                LabelQuote.setText("You’re off to great places, today is your day. Your mountain is waiting, so get on your way.");
                break;
            case 2:
                LabelQuote.setText("You always pass failure on the way to success.");
                break;
            case 3:
                LabelQuote.setText("No one is perfect - that’s why pencils have erasers.");
                break;
            case 4:
                LabelQuote.setText("It always seems impossible until it is done.");
                break;
            case 5:
                LabelQuote.setText("Keep your face to the sunshine and you cannot see a shadow.");
                break;
            case 6:
                LabelQuote.setText("Positive thinking will let you do everything better than negative thinking will.");
                break;
            case 7:
                LabelQuote.setText("The only time you fail is when you fall down and stay down.");
                break;
            case 8:
                LabelQuote.setText("If opportunity doesn’t knock, build a door.");
                break;
            default://Default condition for if there is a problem
                LabelQuote.setText("A journey of a thousand miles begins with a single step");
                break;
            
        }
    }//GEN-LAST:event_ButtonGenerateQuoteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PositivePractice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PositivePractice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PositivePractice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PositivePractice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PositivePractice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ButtonGenerateQuote;
    private javax.swing.JLabel LabelDescription1;
    private javax.swing.JLabel LabelQuote;
    private javax.swing.JLabel LabelTitle;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
