/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.util.*;
/**
 *
 * @author hamgod
 */
public class DiceGame extends javax.swing.JFrame {
    
    /**
     * Creates new form DiceGame
     */
    public DiceGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelDescription3 = new javax.swing.JLabel();
        LabelTitle = new javax.swing.JLabel();
        BoxSides = new javax.swing.JTextField();
        LabelDescription1 = new javax.swing.JLabel();
        LabelDescription2 = new javax.swing.JLabel();
        BoxGuess = new javax.swing.JTextField();
        BoxDiceRoll = new javax.swing.JTextField();
        ButtonRoll = new javax.swing.JButton();
        LabelDescription4 = new javax.swing.JLabel();
        LabelDescription7 = new javax.swing.JLabel();
        LabelDescription5 = new javax.swing.JLabel();
        LabelDescription6 = new javax.swing.JLabel();
        LabelNumOfCorrect = new javax.swing.JLabel();
        LabelNumOfRolls = new javax.swing.JLabel();
        LabelPercentage = new javax.swing.JLabel();
        LabelNumOfIncorrect = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelDescription3.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        LabelDescription3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDescription3.setText("YOUR GUESS                     DICE ROLL");

        LabelTitle.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        LabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTitle.setText("ULTIMATE DICE GUESSING GAME");

        BoxSides.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        BoxSides.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BoxSides.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxSidesActionPerformed(evt);
            }
        });

        LabelDescription1.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        LabelDescription1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDescription1.setText("PICK HOW MANY SIDES YOU WANT YOUR DICE TO HAVE");

        LabelDescription2.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        LabelDescription2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDescription2.setText("ENTER A NUMBER WITHIN THE RANGE ");

        BoxGuess.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        BoxGuess.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BoxGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxGuessActionPerformed(evt);
            }
        });

        BoxDiceRoll.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        BoxDiceRoll.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BoxDiceRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxDiceRollActionPerformed(evt);
            }
        });

        ButtonRoll.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        ButtonRoll.setText("ROLL");
        ButtonRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRollActionPerformed(evt);
            }
        });

        LabelDescription4.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        LabelDescription4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelDescription4.setText("NUMBER OF ROLLS              :");

        LabelDescription7.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        LabelDescription7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelDescription7.setText("PERCENTAGE OF CORRECT GUESSES:");

        LabelDescription5.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        LabelDescription5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelDescription5.setText("NUMBER OF CORRECT GUESSES    :");

        LabelDescription6.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        LabelDescription6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelDescription6.setText("NUMBER OF INCORRECT GUESSES  :");

        LabelNumOfCorrect.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        LabelNumOfCorrect.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelNumOfCorrect.setText("0");

        LabelNumOfRolls.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        LabelNumOfRolls.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelNumOfRolls.setText("0");

        LabelPercentage.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        LabelPercentage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelPercentage.setText("%0");

        LabelNumOfIncorrect.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        LabelNumOfIncorrect.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelNumOfIncorrect.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LabelDescription1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LabelDescription2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LabelDescription3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BoxGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(ButtonRoll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BoxDiceRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelDescription4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelDescription5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelDescription6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelDescription7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelPercentage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(LabelNumOfIncorrect, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelNumOfCorrect, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelNumOfRolls, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BoxSides, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(LabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelDescription1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BoxSides, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelDescription2)
                .addGap(14, 14, 14)
                .addComponent(LabelDescription3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoxGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxDiceRoll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonRoll))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDescription4)
                    .addComponent(LabelNumOfRolls))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDescription5)
                    .addComponent(LabelNumOfCorrect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDescription6)
                    .addComponent(LabelNumOfIncorrect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDescription7)
                    .addComponent(LabelPercentage))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoxSidesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxSidesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxSidesActionPerformed

    private void BoxGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxGuessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxGuessActionPerformed

    private void BoxDiceRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxDiceRollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxDiceRollActionPerformed

    private void ButtonRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRollActionPerformed
        // TODO add your handling code here:
       
        int iSides = Integer.parseInt(BoxSides.getText());
        int iGuess = Integer.parseInt(BoxGuess.getText());
        int iRolls = Integer.parseInt(LabelNumOfRolls.getText());
        int iCorrect = Integer.parseInt(LabelNumOfCorrect.getText());
        int iIncorrect = Integer.parseInt(LabelNumOfIncorrect.getText());
        
        int iRoll = (int)(Math.random()*iSides+1);
        double dPercent;
        String sPercent;
        
        iRolls+=1;
        if(iGuess==iRoll){
            iCorrect+=1;
        }else{
            iIncorrect+=1;
        }
        
        dPercent = 100.0*(iCorrect*1.0/iRolls*1.0);
        sPercent = String.format("%.2f",dPercent)+"%";
        
        BoxDiceRoll.setText(String.valueOf(iRoll));
        LabelNumOfRolls.setText(String.valueOf(iRolls));
        LabelNumOfCorrect.setText(String.valueOf(iCorrect));
        LabelNumOfIncorrect.setText(String.valueOf(iIncorrect));
        LabelPercentage.setText(sPercent);
        
    }//GEN-LAST:event_ButtonRollActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiceGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BoxDiceRoll;
    private javax.swing.JTextField BoxGuess;
    private javax.swing.JTextField BoxSides;
    private javax.swing.JButton ButtonRoll;
    private javax.swing.JLabel LabelDescription1;
    private javax.swing.JLabel LabelDescription2;
    private javax.swing.JLabel LabelDescription3;
    private javax.swing.JLabel LabelDescription4;
    private javax.swing.JLabel LabelDescription5;
    private javax.swing.JLabel LabelDescription6;
    private javax.swing.JLabel LabelDescription7;
    private javax.swing.JLabel LabelNumOfCorrect;
    private javax.swing.JLabel LabelNumOfIncorrect;
    private javax.swing.JLabel LabelNumOfRolls;
    private javax.swing.JLabel LabelPercentage;
    private javax.swing.JLabel LabelTitle;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
